In [1]:
import sklearn
print('The scikit-learn version is ', sklearn.__version__)

The scikit-learn version is  1.4.2


In [2]:
from sklearn import set_config
set_config(display="diagram")

In [3]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=0)

X = [[1,2,3],
     [11,12,13]]

Y = [0,1]

model.fit(X,Y)

RandomForestClassifier(random_state=0)

In [4]:
model.predict(X)

array([0, 1])

In [5]:
model.predict([[14,15,16],[4,5,6]])

array([1, 0])

In [7]:
model.predict_proba([[14,15,16],[4,5,6]])

array([[0.22, 0.78],
       [0.7 , 0.3 ]])

In [8]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

X, y = load_iris(return_X_y=True)

clf = LogisticRegression(random_state=0, max_iter=1000).fit(X, y)

In [9]:
clf.predict(X[:2, :])

array([0, 0])

In [10]:
clf.predict_proba(X[:100, :])

array([[9.81567879e-01, 1.84321062e-02, 1.45963860e-08],
       [9.71308724e-01, 2.86912461e-02, 3.03926427e-08],
       [9.85253153e-01, 1.47468344e-02, 1.24323736e-08],
       [9.76030689e-01, 2.39692713e-02, 3.99938516e-08],
       [9.85218531e-01, 1.47814571e-02, 1.20892748e-08],
       [9.70207024e-01, 2.97929019e-02, 7.44347526e-08],
       [9.86750028e-01, 1.32499515e-02, 2.01427316e-08],
       [9.76127344e-01, 2.38726283e-02, 2.79167402e-08],
       [9.79591480e-01, 2.04084893e-02, 3.08439697e-08],
       [9.68741437e-01, 3.12585309e-02, 3.19328091e-08],
       [9.76223615e-01, 2.37763654e-02, 1.94865970e-08],
       [9.75182969e-01, 2.48169868e-02, 4.42608997e-08],
       [9.74204277e-01, 2.57957014e-02, 2.16636624e-08],
       [9.91855545e-01, 8.14445069e-03, 3.92440039e-09],
       [9.88014444e-01, 1.19855534e-02, 2.85961468e-09],
       [9.86646763e-01, 1.33532235e-02, 1.30155773e-08],
       [9.87955710e-01, 1.20442802e-02, 9.32583137e-09],
       [9.81317145e-01, 1.86828

In [11]:
X[:100, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
y[0:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
clf.score(X,y)

0.9733333333333334

In [14]:
from sklearn.preprocessing import StandardScaler
import numpy as np

X = np.array([1,2,3,4,5,6]).reshape(-1,1)

# scale data according to computed scaling values
Fx = StandardScaler().fit(X)

Fx.transform(X)

array([[-1.46385011],
       [-0.87831007],
       [-0.29277002],
       [ 0.29277002],
       [ 0.87831007],
       [ 1.46385011]])

In [15]:
StandardScaler().fit(X).transform(X)

array([[-1.46385011],
       [-0.87831007],
       [-0.29277002],
       [ 0.29277002],
       [ 0.87831007],
       [ 1.46385011]])